name: CI/CD Pipeline

on:
  push:
    branches: [ main ]  # Adjust this to your main branch name
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  IMAGE_NAME: majidni/tracing-demo-app

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # Fetch all history for all tags and branches

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Check for Changes
      id: check_changes
      run: |
        CHANGES=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep 'source_code/' || true)
        echo "CHANGES_IN_SOURCE=$CHANGES" >> $GITHUB_ENV
        echo "Changes in source_code/: $CHANGES"

    - name: Build
      if: env.CHANGES_IN_SOURCE != ''
      run: |
        cd source_code
        python setup.py sdist

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Push Docker image
      if: env.CHANGES_IN_SOURCE != ''
      uses: docker/build-push-action@v2
      with:
        context: ./source_code
        push: true
        tags: ${{ env.IMAGE_NAME }}:${{ github.sha }}
        labels: |
          release-version=${{ github.sha }}
          branch-name=${{ github.ref }}
